config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks"}
  root 'shared#home'

  get '/about', to: 'shared#about', as: 'about'

  get 'all_products', to: 'products#all_products'

  post 'signups/create', to: 'shared#create', as: 'signups'

  get 'newsletter/new', to: 'newsletter#new', as: 'newsletter'

  resources :carts do
  	resources :products
  end

  resources :categories do
  	resources :products
  end

  resources :products do
  	resources :comments
  end

  resources :newsletter

end

app/controllers/newsletter_controller.rb
class NewsletterController < ApplicationController
  def new
  end

    def create
    NewsletterJob.perform_later({
      emails: params[:emails],
      subject: params[:subject],
      newsletter: params[:newsletter]
      })
      flash[:success] = 'T-Shirt Town Newsletter sent!'
      redirect_to new_newsletter_path
    end

end

app/views/newsletter/new.html.erb
<h1 class="brown-text">Send a T-Shirt Townletter</h1>
<div class="container">
<%= form_tag newsletter_index_path do %>
  <div class="input-field">
    <%= label_tag 'Subject' %>
    <%= text_field_tag 'subject', nil, cols: '20', rows: '6', required: true %>
  </div>
  <div class="input-field">
    <%= label_tag 'Emails (*comma separated)' %>
    <%= text_field_tag 'emails', nil, required: true, cols: '20', rows: '6' %>
  </div>
  <div class="input-field">
    <%= label_tag 'Newsletter Type' %>
  <br />
    <%= select_tag "newsletter", options_for_select(['weekly', 'monthly']) %>
  </div>
  <div class="input-field">
    <%= submit_tag 'Send', class: 'orange darken-4 btn' %>
  </div>
<% end %>
</div>