config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks"}
  root 'shared#home'

  get '/about', to: 'shared#about', as: 'about'

  get 'all_products', to: 'products#all_products'

  post 'signups/create', to: 'shared#create', as: 'signups'

  get 'newsletter/new', to: 'newsletter#new', as: 'newsletter'

  resources :carts do
  	resources :products
  end

  resources :categories do
  	resources :products
  end

  resources :products do
  	resources :comments
  end

  resources :newsletter

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  belongs_to :user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :set_category, only: [:edit, :update, :show, :destroy]
skip_before_action :authenticate_user!, only: [:index]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = current_user.categories.new
  end

  def create
    @category = current_user.categories.new(category_params)
    if @category.save
      redirect_to category_products_path(@category)
    else
      render :new
    end
  end

  def edit
    if current_user.id != @category.user_id
      flash[:error] = 'That shop does not belong to you!'
      redirect_to categories_path
    end
  end

  def update
    if @category.update(category_params)
      redirect_to category_products_path(@category)
    else
      render :edit
    end
end

  def destroy
    if current_user.id != @category.user_id
      flash[:error] = 'That shop does not belong to you!'
      redirect_to categories_path
    else
      @category.destroy
      redirect_to categories_path
    end
  end

  private
  def category_params
    params.require(:category).permit(:style)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

  <div class="field">
    <%= f.label 'Shop Name' %>
    <%= f.text_field :style %>
  </div>
<%= f.submit 'Submit', class: "brown btn white-text" %>

<% end %>

app/views/categories/edit.html.erb
<h2 class="brown">Editing Shop: <%=@category.style %></h2>

<%= render 'form', category: @category %>
<br /><br />
<%= link_to 'Show', @category, class: 'brown-text' %> |
<%= link_to 'Back', categories_path, class: 'brown-text' %>

app/views/categories/index.html.erb
<h2 class="brown">Shops</h2>
<% if @categories.any? %>
  <table>
    <thead>
      <tr>
        <th>Shop Name</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= link_to category.style, category_products_path(category) %></td>
            <% if user_signed_in? %>
            <% if current_user.id == category.user_id %>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3>No shops yet, add one!</h3>
<% end %>

<br>
<%= link_to "Add Shop", new_category_path, class: 'brown btn' %>

app/views/categories/new.html.erb
<div class="container">
<h2 class="brown">New Shop</h2>

<%= render 'form', category: @category %>
<br /><br />
<%= link_to 'Back', categories_path, class: "brown-text text-lighten-2" %>
</div>

app/views/categories/show.html.erb
<div class="row">
        <div class="col s12 center">
          <div class="card grey">
            <div class="card-content white-text">
              <span class="card-title">Shop: <%= @category.style %> </span>
              <p>Products <%= @products.name %> </p>
            </div>

            <div class="card-action">
              <%= link_to 'Edit', edit_category_path(@category), class: "brown-text" %>
              <%= link_to 'Delete', category_path(@category), method: :delete, data: {confirm: 'Delete this category?'} %>
            </div>
          </div>
          <% if @products.any? %>
          <h4> All Styles </h4>
          <% @products.each do |product| %>
          <div class="">
        <div class="col s12 m3 l6">
          <div class="card brown">
            <div class="card-content white-text">
              <span class="card-title"><%= category.style %></span>

            </div>
            <div class="card-action">
              <%= link_to 'Show', category_product_path(@category, product), class: "brown-text" %>
              <%= link_to 'Edit', edit_category_product_path(@category, product) %>
              <%= link_to 'Delete', category_product_path(@category, product), method: :delete, data: {confirm: 'Delete product?'} %>
            </div>
          </div>
        </div>
      </div>
          <% end %>
        <% end %>