config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks"}
  root 'shared#home'

  get '/about', to: 'shared#about', as: 'about'

  get 'all_products', to: 'products#all_products'

  post 'signups/create', to: 'shared#create', as: 'signups'

  get 'newsletter/new', to: 'newsletter#new', as: 'newsletter'

  resources :carts do
  	resources :products
  end

  resources :categories do
  	resources :products
  end

  resources :products do
  	resources :comments
  end

  resources :newsletter

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :category

  has_attached_file :avatar, styles: {
    large: "500x500>", medium: "400x400>", small: "300x300>", thumb: "150x150#"}, default_url: "app/assets/images/no-image.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_category, except: [:all_products]

  before_action :set_product, except: [:index, :new, :create, :all_products]

  skip_before_action :authenticate_user!, only: [:index, :show, :all_products]


  def index
    @products = @category.products
  end

  def show
    @comments = @product.comments
    @average = @comments.average(:rating)
  end

  def new
    @product = @category.products.new
  end

  def create
    @product = @category.products.new(product_params)
    if @product.save
      redirect_to category_product_path(@category, @product)
    else
      render :new
    end
  end

  def edit
    if current_user.id != @product.category.user_id
      flash[:error] = 'That does not belong to you!'
      redirect_to category_products_path(@category)
    end
  end

  def update
    if @product.update(product_params)
      redirect_to category_product_path(@category, @product)
    else
      render :edit
    end
  end

  def destroy
    if current_user.id != @product.user_id
      flash[:error] = 'That does not belong to you!'
      redirect_to category_products_path(@category)
    else
      @product.destroy
      redirect_to category_products_path(@category)
    end
  end

  def all_products
   @products = Product.all
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price, :inventory, :image, :avatar)
    end

    def set_product
      @product = @category.products.find(params[:id])
    end

    def set_category
      @category = Category.find(params[:category_id])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container">
  <div class="row">
    <%= form_for [@category, @product], html: { multipart: true} do |f| %>
      <div class="col m6">
        <%= f.label :name, class: 'brown-text' %>
        <%= f.text_field :name, required: true %>
      </div>
      <div class="col m6">
        <%= f.label :description %>
        <%= f.text_field :description %>
      </div>
      <div class="col m6">
        <%= f.label :price %>
        <%= f.number_field :price, value: number_to_currency(f.object.price.to_f, delimiter: '', unit: ''), step: :any %>
      </div>
      <div class="col m6">
        <%= f.label :inventory %>
        <%= f.number_field :inventory %>
      </div>
      <div class="file-field input-field col s6 offset-s4">
        <div class="btn orange accent-4">
          <span>Add Image</span>
        </div>
        <div class="file-path-wrapper">
          <!--<input class="file-path validate" type="text">-->
          <%= f.file_field :avatar %>
        </div>
      </div>
      </div>
      <div class="center">
      <%= f.submit class: "btn brown white-text" %>
       </div>
    <% end %>

  </div>
</div>

app/views/products/all_products.html.erb
<h2>all products</h2>

<% if @products.any? %>
  <h3 class="brown-text">Products</h3>
    <div class="row">
      <% @products.each do |product| %>
        <div class="col s12 m6 l6">
          <div class="card medium hoverable">
           <div class="card-image waves-effect waves-light waves-block">
              <%= image_tag product.avatar.url(:medium), class: "activator" %>
           </div>
             <div class="card-content brown-text">
               <span class="card-title"> <%= product.name %> </span>
               <p> Price: <%= product.price %> </p>
             </div>
           <div class="card-action">
             <%= link_to 'Show', category_product_path(product.category, product), :class => "brown-text text-lighten-2" %>
             <% if user_signed_in? %>
             <% if current_user.id == product.category.user_id %>
             <%= link_to 'Edit', edit_category_product_path(product.category, product), class: "brown-text text-lighten-2" %>
             <%= link_to 'Delete', category_product_path(product.category, product), class: "brown-text text-lighten-2", method: :delete, data: {confirm: 'Really Delete?'} %>
             <% end %>
             <% end %>
           </div>
           <div class="card-reveal">
             <span class="card-title grey-text text-darken-4"><%= product.name %>
             <p><%= product.description %></p>
             <i class="material-icons right">close</i>
             </span>
           </div>
           </div>
       </div>
      <% end %>
    </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product <%= @product.name %></h1>

<%= render(partial: 'form') %>

app/views/products/index.html.erb
<div class="container">
<h2 class="teal-text">Category: <%= @category.style %> </h2>

<% if @products.any? %>
  <h3 class="teal-text">Products</h3>
    <div class="row">
      <% @products.each do |product| %>
        <div class="col s12 m6 l6">
          <div class="card medium hoverable">
           <div class="card-image waves-effect waves-light waves-block">
              <%= image_tag product.avatar.url(:medium), class: "activator" %>
        </div>
             <div class="card-content teal-text">
               <span class="card-title"> <%= product.name %> </span>
               <p> Price: <%= product.price %> </p>
             </div>
           <div class="card-action">
             <%= link_to 'Show', category_product_path(@category, product), :class => "brown-text text-lighten-2" %>
             <%= link_to 'Edit', edit_category_product_path(@category, product), class: "brown-text text-lighten-2" %>
             <%= link_to 'Delete', category_product_path(@category, product), class: "brown-text text-lighten-2", method: :delete, data: {confirm: 'Really Delete?'} %>
           </div>
           <div class="card-reveal">
             <span class="card-title grey-text text-darken-4"><%= product.name %>
             <p><%= product.description %></p>
             <i class="material-icons right">close</i>
             </span>
           </div>
           </div>
       </div>
      <% end %>
    </div>
<% end %>

  <%= link_to 'Add Product', new_category_product_path(@category), class: 'btn brown' %>
</div>

app/views/products/new.html.erb
<div class="container">
<h2>Add Product for Category: <%= @category.style %></h2>
</div>

<%= render(partial: 'form') %>

app/views/products/show.html.erb
<%= link_to "View All #{@category.style} Products", category_products_path(@category), class: 'btn brown' %>

<div class='center'>
<h1 class='brown-text'><%= @product.name %></h1>


<div class="container">
  Name: <i><%= @product.name %></i>
  <br />
  Description: <i><%= @product.description %></i>
  <br />
  Price: $<i><%= @product.price %></i>
  <br />
  Quantity on-hand: <i><%= @product.inventory %></i>
  <br />
  Image: <i><%= image_tag @product.avatar.url(:medium) %></i>
</div>
<br /><br />
<% if user_signed_in? %>
  <% if current_user.id == @category.user_id %>
<div class="container">
<%= link_to 'Edit', edit_category_product_path(@category, @product), class: "brown-text text-lighten-2" %> |
<%= link_to 'Delete', category_product_path(@category, @product), class: "brown-text text-lighten-2", method: :delete, data: {confirm: 'Really Delete Product?'} %>
</div>
<% end %>
<% end %>
<br /><br />
<hr />

<br /><br />
</div>

<h3 class="center">Comments for <%= @product.name %></h3>
<br>

<div class="container">

	<% if @product.comments.any? %>
	<h4 class="center">Average Rating: <%= @average.round(1) %></h4>
		<div class="row">
			<% @product.comments.each do |comment| %>
				<div class="col s12">
			  	<div class="card white">
			    	<div class="card-content teal-text">
			      	<span class="card-title">Rating: <%= comment.rating %></span>
			      	<p><%= comment.review %></p>
			    	</div>
			    	<div class="card-action">
			    		<%= link_to 'Edit', edit_product_comment_path(@product, comment), :class => "brown-text text-lighten-2" %>
			    		<%= link_to 'Delete', product_comment_path(@product, comment), method: :delete, data: {confirm: 'Really delete comment?'}, :class => "brown-text text-lighten-2" %>
			   		</div>
			  	</div>
				</div>
			<% end %>
		</div>
	<% else %>
		<h5 class="center">This product has no comments.</h5>
	<% end %>

	<div class="center">
		<%= link_to 'Add Comment', new_product_comment_path(@product), class: 'btn brown' %>
	</div>
</div>